version: '3'

services:
    api:
        image: roblancas/challenge-api 
        ports: 
          - 8000:8000
        env_file:
          - ./environments/production.env
        depends_on: 
          - postgres
        #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
        

    postgres:
        image: postgres
        environment: 
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
        volumes:
          - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: 