version: '3'

services:
    api:
        build: . 
        ports: 
          - 8000:8000
        volumes:
          - ./:/usr/src/app
        environment:
          - SENDER_EMAIL=
          - SENDER_PASSWORD=
          - RECIPIENT_EMAIL=
          - POSTGRES_USER=
          - POSTGRES_PASSWORD=
          - POSTGRES_HOST=
          - DATABASE_PORT=
          - POSTGRES_DB=
          - SECRET_KEY=
          - ALGORITHM=HS256
          - ACCESS_TOKEN_EXPIRE_MINUTES=10
        depends_on: 
          - postgres
        command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload 
        

    postgres:
        image: postgres
        environment: 
          - POSTGRES_PASSWORD=
          - POSTGRES_DB=
        volumes:
          - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: 